### PR TITLE
Added jog increment toggle buttons

### PR DESCRIPTION
**Pull request by kevinastone**
Provide a button group of checked buttons that toggle between continuous
and incremental jog modes.

(I'm very new to qt-designer and this code-base, so please provide guidance if this is the correct style and implementation).

Screenshot_2021-06-04_13-18-54
Screenshot_2021-06-04_13-18-26

### CODE REVIEW

**Comment by silopolis** [comment]
Hi,

That's very nice!
Is the "Incr" button really needed?
Toggling one of the increments switches to incremental mode while "cont"
brings you back to continuous.



Le ven. 4 juin 2021 à 20:42, Kevin Stone ***@***.***> a
écrit :

**Comment by kevinastone** [comment]
> Is the "Incr" button really needed? Toggling one of the increments switches to incremental mode while "cont" brings you back to continuous.

It would depend on how it's implemented.  I've attempted to mimic how Tormach's PathPilot is implemented where a single button toggles between Incremental and Continuous mode.  PyQT would require a custom toggle button, so I just used a button group with Checked PushButtons to achieve the same.

controller_ui_2x


For a safety or operator ease of use, I think it's beneficial to quickly see which mode you're in as well as the current increment distance.  So toggling to increment mode is a single action vs re-selecting the desired increment distance.

My next goal would be to implement the keyboard shortcuts from Axis (C for continuous, I for incremental) to make it easier to precisely jog with the keyboard.  If continuous is just another jog increment setting, this doesn't work (well) to quickly switch between the modes.

**Comment by kevinastone** [comment]
What do we think about this change?  I'd like to find a way to merge this upstream so I don't continue to maintain my own fork indefinitely.

**Comment by TurBoss** [comment]
hello,
  I just tested, sorry for the delay.

it works like a charm in the python3 branch but I don't have a pytho2 setup

I'll try to merge in python2 branch so it can be tested

Thank you so much

**Comment by TurBoss** [comment]
Hello

If you add "JOG" to the increments line in the display section of the ini 

```
[DISPLAY]
INCREMENTS = JOG .1in .01in .001in .0001in
```
or metric

Click on "jog" button toggles jog mode and any other changes to incremental mode
Without jog it doesn't have the toggle


this is not really needed at all if configured this way 

we don't realy want to mimic PP 

thank you

**Pull request closed without merging**
